name: Clean First Time
favicon: null
layout_spectrum: 0.2915053078904748
typography_spectrum: 0.06317775673232973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.060307665495201945
  lightness: 0.2756859650835395
  saturation: 0.5367622391786426
  rhythmicContrast: 0.8302062866277993
purpose: []
