name: Clean First Time
favicon: null
layout_spectrum: 0.2915053078904748
typography_spectrum: 0.06317775673232973
title: Clean First Time
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00597d'
    - '#93bf80'
    - '#5a97aa'
    - '#26718f'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.5367622391786426
  rhythmicContrast: 0.5
purpose: []
